CREATE SCHEMA knowledge;
USE knowledge;
CREATE TABLE IF NOT EXISTS `tutorial` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `content` LONGTEXT,
    `createAt` DATETIME,
    `updatedAt` DATETIME,
    `group` VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS `group` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS `tutorial_group` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `idTutorial` INTEGER NOT NULL,
    `idGroup` INTEGER NOT NULL,
    CONSTRAINT `FK_ID_TUTORIAL` FOREIGN KEY (`idTutorial`) REFERENCES `tutorial`(`id`),
    CONSTRAINT `FK_ID_GROUP` FOREIGN KEY (`idGroup`) REFERENCES `group`(`id`)
);